### ISSUE TITLE
Customizing styles and layout

### ISSUE THREAD

**Issue by ofyalcin** [boospot/boo-settings-helper#1]
Thank you for this wonderful framework!

Is it possible to customize styles and layouts as we want using this framework?

**Comment by boospot** [comment]
@ofyalcin 
You are welcome.

I would call it a helper class rather than framework ;)
This class is using the basics of the Settings API offered by WordPress at its core.
It does not add anything extra.

So, the styles and layouts offered are only those as WordPress Settings API allows.
Nothing more, nothing less.

The prime objective of this class is to make it easy to deal with Settings API.

If you need more control as to layout and stuff. I would recommend you checkout:
https://github.com/wpmetabox/meta-box
https://github.com/JoeSz/Exopite-Simple-Options-Framework
https://www.advancedcustomfields.com/pro/

hope it helps.
